// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllEntriesInCurrentRoot() {
  return window['go']['filesystem']['Filesystem']['GetAllEntriesInCurrentRoot']();
}

export function GetRoot() {
  return window['go']['filesystem']['Filesystem']['GetRoot']();
}

export function SetRoot(arg1) {
  return window['go']['filesystem']['Filesystem']['SetRoot'](arg1);
}
