// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {filesystem} from '../models';

export function GetAll(arg1:string):Promise<Array<filesystem.Entry>>;

export function GetRoot():Promise<filesystem.FilePath>;

export function SetRoot(arg1:string):Promise<void>;
