// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {platform} from '../models';

export function GetPlatform():Promise<platform.PlatformName>;
